### ISSUE TITLE
Convert UTF-16 from e.g. comments into UTF-8?

### ISSUE THREAD

**Issue by highend** [bogem/id3v2#53] opened 2020-03-24 22:58 UTC
Hi,

I'd like to print the comment field to the console (under Windows in this case). This doesn't really work well^^ if that field was stored with UTF-16 BOM encoding before, e.g. by MP3Tag.
Is there any way to tell the library that I get a (converted) UTF-8 string instead?
The console supports UTF-8 and with the right font this would result in some readable text :)

```
                comments := tag.GetFrames(tag.CommonID("Comments"))
                for _, v := range comments {
                    comment, ok := v.(id3v2.CommentFrame)
                    if !ok {
                        log.Fatal("Couldn't assert comment frame")
                    }
                    fmt.Printf("\nComment: %s", comment.Text)
                    fmt.Printf("\nComment: %s", comment.Encoding)
                }
```
ATM it looks like this: 
```
Comment: �C o m m e n t
Comment: UTF-16 encoded Unicode with BOM
```

The original comment is really "Comment" for testing purposes...

**Comment by bogem** [comment] 2020-03-25 05:37
Hi! id3v2 should automatically convert UTF-16 text to UTF-8 and it should correctly print the comment. So it's a bug, but the latest release should fix some UTF-16 issues. Do you use the latest version? Try to `go get -u github.com/bogem/id3v2`

**Comment by highend** [comment] 2020-03-25 06:01
Hi,

yeah, I'm already on the latest version:

```
git log
commit 3da57733453b434afc02a084236bbe86209c6974 (HEAD -> master, tag: v1.1.2, origin/master, origin/HEAD)
Author: Albert Nigmatzianov <albertnigma@gmail.com>
Date:   Tue Mar 10 08:47:07 2020 +0100

    Support older versions and 32bit
```

**Comment by bogem** [comment] 2020-03-25 07:02
Hm okay, that's weird. Can you please send the file, so I can reproduce the bug?

**Comment by highend** [comment] 2020-03-25 07:40
Here is the link for the zip file that contains the mp3: https://filebin.net/eemwrdr40a27e876

The ID3v2.3 + ID3v1 tags have been created with MP3Tag.
Settings:
```
[x] ID3v1
[x] ID3v2
    (o) ID3v2.3 UTF-16
```

**Comment by qkveri** [comment] 2020-03-25 10:54
I have the same problem.

Go 1.14.1
macOS 10.15.3

![image](https://user-images.githubusercontent.com/26967934/77529002-ef305900-6e9f-11ea-8caf-d83b132cabe6.png)

**Comment by bogem** [comment] 2020-03-25 19:24
*(Information for me)* 

**Reason of problem**: description of comment is empty string encoded in UTF-16 with BOM. id3v2 doesn't consider this situation.

**Comment by bogem** [comment] 2020-03-25 19:37
Should be fixed in https://github.com/bogem/id3v2/commit/051e4b2ea87f4646bab6d86642dce1448346a402. Please check 🙏

**Closed** 2020-03-25 19:36 UTC

**Comment by qkveri** [comment] 2020-03-25 20:58
This works for me.
Thanks!

Please add a new release for use with go mod.

**Comment by highend** [comment] 2020-03-25 21:27
Works for me as well, tested all combinations of MP3Tag options, the output is encoded fine (for comments).
Thanks!

**Comment by bogem** [comment] 2020-03-26 05:45
@qkveri [Done!](https://github.com/bogem/id3v2/releases/tag/v1.1.3)

You're welcome guys 🙂
